# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Install project dependencies for the Juice Shop application
- script: |
    npm install
  displayName: 'Install Project Dependencies'

# 2. SCA (Software Composition Analysis) scan using native npm audit
- script: |
    npm audit --audit-level=high
  displayName: 'Component Security Scan (SCA)'
  continueOnError: true # Keeps the pipeline running despite finding flaws (ideal for the intentionally vulnerable Juice Shop)

# 3. Secret Scanning to detect hardcoded keys, tokens, or passwords
- script: |
    docker run -v $(System.DefaultWorkingDirectory):/path zricethezaza/gitleaks:latest detect --source=/path --verbose
  displayName: 'Credential Exposure Scan (Secret Scanning)'
  continueOnError: true