# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Instalar as dependências do projeto Juice Shop
- script: |
    npm install
  displayName: 'Install Project Dependencies'

# 2. Análise de SCA (vulnerabilidades em dependências de terceiros)
- script: |
    npm audit --audit-level=high
  displayName: 'Component Security Scan (SCA)'
  continueOnError: true

# 3. Secret Scanning (verificar se há senhas ou chaves expostas no código)
- script: |
    docker run -v $(System.DefaultWorkingDirectory):/path zricethezaza/gitleaks:latest detect --source=/path --verbose
  displayName: 'Credential Exposure Scan (Secret Scanning)'
  continueOnError: true

# 4. SAST com Semgrep
- script: |
    docker run --rm -v "$(System.DefaultWorkingDirectory):/src" returntocorp/semgrep semgrep scan --config=auto
  displayName: 'Lightweight SAST Scan (Semgrep)'
  continueOnError: true

# 5. Execução do SonarQube Cloud via Docker (Contornando o bloqueio de binding)
- script: |
    docker run --rm \
      -v "$(System.DefaultWorkingDirectory):/usr/src" \
      sonarsource/sonar-scanner-cli \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.token=ffaeb771ebd201df028aa9184423838651475bd2 \
      -Dsonar.organization=ivaridev-sandbox \
      -Dsonar.projectKey=devsecops-pipeline \
      -Dsonar.projectName=devsecops-pipeline \
      -Dsonar.sources=.
  displayName: 'Deep SAST & Code Quality Scan (SonarQube Cloud)'
  continueOnError: true

# 6. Execução do Scan do SonarQube Cloud
- task: SonarCloudAnalyze@3
  displayName: 'Deep SAST & Code Quality Scan (SonarQube Cloud)'
  continueOnError: true

# 7. Publicação dos resultados
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube Cloud Quality Gate Results'